replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/bt-play-355619/gitops/bookinfo-processor
  tag: "1.0.5-SNAPSHOT"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80 # Default service port

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

nodeSelector: {}

tolerations: []

# ConfigMap settings for the processor service
configMap:
  enabled: true
  data:
    PROCESSOR_MODE: "normal"
    MAX_THREADS: "4"
    CACHE_EXPIRY: "120"
    LOG_LEVEL: "warn"
    PROCESSOR_ENV: "default"

env:
  - name: ENVIRONMENT
    value: ""

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
